### ISSUE TITLE
Not appearing for some reason

### ISSUE THREAD

**Issue by ghost** [nwootton/MMM-UKNationalRail#3]
To your troubleshoot questions
1. YES
2. YES
3. YES (RDH) 
3. Sorry I'm a bit of a noob not sure what this is asking
4. Same as previous
5. So the code is RDH (redhill) trying to set this up for my girlfriends commute.

This app looks fantastic. I've had the magic mirror running for a while with a news feed, tube status (for our old address), local weather etc. I'm really not expert at this so I could be missing something obvious. Basically it just doesn't show up on the display. I've set position to 'middle_centre' put in crs and got the api id and key data input and double checked them. Any ideas? Thanks for your time!

**Comment by ghost** [comment]
Just as a follow up I've tried setting Waterloo (WAT) and had the same issue.. Definitely something on my end!

**Comment by nwootton** [comment]
So - if the issue is setup - you should be posting on the topic on the forum. Issues relates to bugs in the code.

**Comment by ghost** [comment]
ah sorry mate, will post there this evening to see if anyone can help. cheers.

**Comment by nwootton** [comment]
So testing the RDH code in the TransportAPI returns results. Adding the code to the Magic Mirror 2.2.2 version of the code returns results:
![screen shot 2018-04-03 at 12 48 52](https://user-images.githubusercontent.com/7591978/38247558-a9f466a6-373d-11e8-9f4f-584117d4baab.png)

Updating MagicMirror to the new 2.3.1 version also returns results:
![screen shot 2018-04-03 at 12 49 26](https://user-images.githubusercontent.com/7591978/38247563-ae2a9bbe-373d-11e8-8a46-164b1835209d.png)

**Update**
Complete install from git again still returns results:
![screen shot 2018-04-03 at 12 54 13](https://user-images.githubusercontent.com/7591978/38247749-3b05310c-373e-11e8-993c-c036727616d6.png)

Sorry looks like the issue is with your setup - so the best place to ask would be the forum. If you want to do a quick sanity check of the JSON, copy the contents of the file and paste it in jsonlint.com - that will tell you if there are any formatting errors.
